### ISSUE TITLE
Typed Property Error

### ISSUE THREAD

**Issue by ghost** [nystudio107/craft-units#41]
### Describe the bug

I installed Units, and now I get the error below after I tried to create a Units field, as well as whenever I try to edit any existing field. Everything works fine again after I uninstall Units.

```
Error: Typed property nystudio107\units\models\Settings::$defaultMax must not be accessed before initialization in /app/vendor/nystudio107/craft-units/src/fields/Units.php:105
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): nystudio107\units\fields\Units->init()
#1 /app/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#2 [internal function]: craft\base\Model->__construct(Array)
#3 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#4 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('nystudio107\\uni...', Array, Array)
#5 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('nystudio107\\uni...', Array, Array)
#6 /app/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#7 /app/vendor/craftcms/cms/src/helpers/Component.php(121): Craft::createObject(Array)
#8 /app/vendor/craftcms/cms/src/services/Fields.php(593): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#9 /app/vendor/craftcms/cms/src/controllers/FieldsController.php(326): craft\services\Fields->createField(Array)
#10 [internal function]: craft\controllers\FieldsController->actionSaveField()
#11 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#14 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('fields/save-fie...', Array)
#15 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('fields/save-fie...', Array)
#16 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /app/web/index.php(12): yii\base\Application->run()
#19 {main}
```
### To reproduce
Steps to reproduce the behaviour:
1. Install Units
2. Try to edit any field; get the error above
3. Uninstall Units
4. Things work as they should

### Versions
- Plugin version: Units 4.0.0
- Craft version: Craft Pro 4.0.3

**Comment by AndrewMac** [comment]
Still having this problem, I'm afraid … now Craft 4.2.7

**Comment by danieltott** [comment]
I had the same issue - was able to get around it by copying `vendor/nystudio107/craft-units/src/config.php` to `config/units.php`

**Comment by khalwat** [comment]
hmmmm sorry, somehow I missed this issue being filed!

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-units/commit/5068b0549a58a5ca774d2aca14abec55469f0fc2

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-units": "dev-develop-v4 as 4.0.1”,
```
Then do a `composer clear-cache && composer update`
